/* tslint:disable */
/* eslint-disable */
/**
 * Donator-Mainframe communication
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Bundesland,
  Wahl,
  Wahlkreis,
} from '../models/index';
import {
    BundeslandFromJSON,
    BundeslandToJSON,
    WahlFromJSON,
    WahlToJSON,
    WahlkreisFromJSON,
    WahlkreisToJSON,
} from '../models/index';

/**
 * 
 */
export class GeneralApi extends runtime.BaseAPI {

    /**
     */
    async getBundeslaenderRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Bundesland>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bundeslaender`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BundeslandFromJSON));
    }

    /**
     */
    async getBundeslaender(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Bundesland>> {
        const response = await this.getBundeslaenderRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getWahlenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Wahl>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/wahlen`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WahlFromJSON));
    }

    /**
     */
    async getWahlen(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Wahl>> {
        const response = await this.getWahlenRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getWahlkreiseRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Wahlkreis>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/wahlkreise`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WahlkreisFromJSON));
    }

    /**
     */
    async getWahlkreise(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Wahlkreis>> {
        const response = await this.getWahlkreiseRaw(initOverrides);
        return await response.value();
    }

}
