/* tslint:disable */
/* eslint-disable */
/**
 * Donator-Mainframe communication
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Abgeordneter,
  ClosestWinners,
  SeatDistribution,
  Stimmanteil,
} from '../models/index';
import {
    AbgeordneterFromJSON,
    AbgeordneterToJSON,
    ClosestWinnersFromJSON,
    ClosestWinnersToJSON,
    SeatDistributionFromJSON,
    SeatDistributionToJSON,
    StimmanteilFromJSON,
    StimmanteilToJSON,
} from '../models/index';

export interface GetAbgeordneteRequest {
    wahlid: number;
}

export interface GetClosestWinnersRequest {
    wahlid: number;
}

export interface GetSitzverteilungRequest {
    wahlid: number;
}

export interface GetStimmanteilRequest {
    wahlid: number;
    wahlkreisid: number;
}

/**
 * 
 */
export class GlobalApi extends runtime.BaseAPI {

    /**
     */
    async getAbgeordneteRaw(requestParameters: GetAbgeordneteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Abgeordneter>>> {
        if (requestParameters['wahlid'] == null) {
            throw new runtime.RequiredError(
                'wahlid',
                'Required parameter "wahlid" was null or undefined when calling getAbgeordnete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/results/{wahlid}/abgeordnete`.replace(`{${"wahlid"}}`, encodeURIComponent(String(requestParameters['wahlid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AbgeordneterFromJSON));
    }

    /**
     */
    async getAbgeordnete(requestParameters: GetAbgeordneteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Abgeordneter>> {
        const response = await this.getAbgeordneteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getClosestWinnersRaw(requestParameters: GetClosestWinnersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ClosestWinners>>> {
        if (requestParameters['wahlid'] == null) {
            throw new runtime.RequiredError(
                'wahlid',
                'Required parameter "wahlid" was null or undefined when calling getClosestWinners().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/results/{wahlid}/closestwinners`.replace(`{${"wahlid"}}`, encodeURIComponent(String(requestParameters['wahlid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ClosestWinnersFromJSON));
    }

    /**
     */
    async getClosestWinners(requestParameters: GetClosestWinnersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ClosestWinners>> {
        const response = await this.getClosestWinnersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSitzverteilungRaw(requestParameters: GetSitzverteilungRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SeatDistribution>> {
        if (requestParameters['wahlid'] == null) {
            throw new runtime.RequiredError(
                'wahlid',
                'Required parameter "wahlid" was null or undefined when calling getSitzverteilung().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/results/{wahlid}/sitzverteilung`.replace(`{${"wahlid"}}`, encodeURIComponent(String(requestParameters['wahlid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SeatDistributionFromJSON(jsonValue));
    }

    /**
     */
    async getSitzverteilung(requestParameters: GetSitzverteilungRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SeatDistribution> {
        const response = await this.getSitzverteilungRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getStimmanteilRaw(requestParameters: GetStimmanteilRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Stimmanteil>>> {
        if (requestParameters['wahlid'] == null) {
            throw new runtime.RequiredError(
                'wahlid',
                'Required parameter "wahlid" was null or undefined when calling getStimmanteil().'
            );
        }

        if (requestParameters['wahlkreisid'] == null) {
            throw new runtime.RequiredError(
                'wahlkreisid',
                'Required parameter "wahlkreisid" was null or undefined when calling getStimmanteil().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/results/{wahlid}/stimmanteil`.replace(`{${"wahlid"}}`, encodeURIComponent(String(requestParameters['wahlid']))).replace(`{${"wahlkreisid"}}`, encodeURIComponent(String(requestParameters['wahlkreisid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StimmanteilFromJSON));
    }

    /**
     */
    async getStimmanteil(requestParameters: GetStimmanteilRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Stimmanteil>> {
        const response = await this.getStimmanteilRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
