/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  OverviewWahlkreis,
  Stimmanteil,
  WinningParties,
} from '../models/index';
import {
    OverviewWahlkreisFromJSON,
    OverviewWahlkreisToJSON,
    StimmanteilFromJSON,
    StimmanteilToJSON,
    WinningPartiesFromJSON,
    WinningPartiesToJSON,
} from '../models/index';

export interface GetErststimmenWahlkreisRequest {
    wahlid: number;
    wahlkreisid: number;
    generatefromaggregate?: boolean;
}

export interface GetOverviewWahlkreisRequest {
    wahlid: number;
    wahlkreisid: number;
    generatefromaggregate?: boolean;
}

export interface GetWinningPartiesWahlkreisRequest {
    wahlid: number;
    wahlkreisid: number;
}

export interface GetWinningPartiesWahlkreiseRequest {
    wahlid: number;
}

export interface GetZweitstimmenWahlkreisRequest {
    wahlid: number;
    wahlkreisid: number;
    generatefromaggregate?: boolean;
}

/**
 * 
 */
export class WahlkreisApi extends runtime.BaseAPI {

    /**
     */
    async getErststimmenWahlkreisRaw(requestParameters: GetErststimmenWahlkreisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Stimmanteil>>> {
        if (requestParameters['wahlid'] == null) {
            throw new runtime.RequiredError(
                'wahlid',
                'Required parameter "wahlid" was null or undefined when calling getErststimmenWahlkreis().'
            );
        }

        if (requestParameters['wahlkreisid'] == null) {
            throw new runtime.RequiredError(
                'wahlkreisid',
                'Required parameter "wahlkreisid" was null or undefined when calling getErststimmenWahlkreis().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['generatefromaggregate'] != null) {
            queryParameters['generatefromaggregate'] = requestParameters['generatefromaggregate'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/results/{wahlid}/stimmanteil/erststimmen/wahlkreis/{wahlkreisid}`.replace(`{${"wahlid"}}`, encodeURIComponent(String(requestParameters['wahlid']))).replace(`{${"wahlkreisid"}}`, encodeURIComponent(String(requestParameters['wahlkreisid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StimmanteilFromJSON));
    }

    /**
     */
    async getErststimmenWahlkreis(requestParameters: GetErststimmenWahlkreisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Stimmanteil>> {
        const response = await this.getErststimmenWahlkreisRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getOverviewWahlkreisRaw(requestParameters: GetOverviewWahlkreisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OverviewWahlkreis>> {
        if (requestParameters['wahlid'] == null) {
            throw new runtime.RequiredError(
                'wahlid',
                'Required parameter "wahlid" was null or undefined when calling getOverviewWahlkreis().'
            );
        }

        if (requestParameters['wahlkreisid'] == null) {
            throw new runtime.RequiredError(
                'wahlkreisid',
                'Required parameter "wahlkreisid" was null or undefined when calling getOverviewWahlkreis().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['generatefromaggregate'] != null) {
            queryParameters['generatefromaggregate'] = requestParameters['generatefromaggregate'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/results/{wahlid}/overview/wahlkreis/{wahlkreisid}`.replace(`{${"wahlid"}}`, encodeURIComponent(String(requestParameters['wahlid']))).replace(`{${"wahlkreisid"}}`, encodeURIComponent(String(requestParameters['wahlkreisid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OverviewWahlkreisFromJSON(jsonValue));
    }

    /**
     */
    async getOverviewWahlkreis(requestParameters: GetOverviewWahlkreisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OverviewWahlkreis> {
        const response = await this.getOverviewWahlkreisRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getWinningPartiesWahlkreisRaw(requestParameters: GetWinningPartiesWahlkreisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WinningParties>> {
        if (requestParameters['wahlid'] == null) {
            throw new runtime.RequiredError(
                'wahlid',
                'Required parameter "wahlid" was null or undefined when calling getWinningPartiesWahlkreis().'
            );
        }

        if (requestParameters['wahlkreisid'] == null) {
            throw new runtime.RequiredError(
                'wahlkreisid',
                'Required parameter "wahlkreisid" was null or undefined when calling getWinningPartiesWahlkreis().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/results/{wahlid}/winningparties/wahlkreis/{wahlkreisid}`.replace(`{${"wahlid"}}`, encodeURIComponent(String(requestParameters['wahlid']))).replace(`{${"wahlkreisid"}}`, encodeURIComponent(String(requestParameters['wahlkreisid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WinningPartiesFromJSON(jsonValue));
    }

    /**
     */
    async getWinningPartiesWahlkreis(requestParameters: GetWinningPartiesWahlkreisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WinningParties> {
        const response = await this.getWinningPartiesWahlkreisRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getWinningPartiesWahlkreiseRaw(requestParameters: GetWinningPartiesWahlkreiseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WinningParties>> {
        if (requestParameters['wahlid'] == null) {
            throw new runtime.RequiredError(
                'wahlid',
                'Required parameter "wahlid" was null or undefined when calling getWinningPartiesWahlkreise().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/results/{wahlid}/winningparties/wahlkreis`.replace(`{${"wahlid"}}`, encodeURIComponent(String(requestParameters['wahlid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WinningPartiesFromJSON(jsonValue));
    }

    /**
     */
    async getWinningPartiesWahlkreise(requestParameters: GetWinningPartiesWahlkreiseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WinningParties> {
        const response = await this.getWinningPartiesWahlkreiseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getZweitstimmenWahlkreisRaw(requestParameters: GetZweitstimmenWahlkreisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Stimmanteil>>> {
        if (requestParameters['wahlid'] == null) {
            throw new runtime.RequiredError(
                'wahlid',
                'Required parameter "wahlid" was null or undefined when calling getZweitstimmenWahlkreis().'
            );
        }

        if (requestParameters['wahlkreisid'] == null) {
            throw new runtime.RequiredError(
                'wahlkreisid',
                'Required parameter "wahlkreisid" was null or undefined when calling getZweitstimmenWahlkreis().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['generatefromaggregate'] != null) {
            queryParameters['generatefromaggregate'] = requestParameters['generatefromaggregate'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/results/{wahlid}/stimmanteil/zweitstimmen/wahlkreis/{wahlkreisid}`.replace(`{${"wahlid"}}`, encodeURIComponent(String(requestParameters['wahlid']))).replace(`{${"wahlkreisid"}}`, encodeURIComponent(String(requestParameters['wahlkreisid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StimmanteilFromJSON));
    }

    /**
     */
    async getZweitstimmenWahlkreis(requestParameters: GetZweitstimmenWahlkreisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Stimmanteil>> {
        const response = await this.getZweitstimmenWahlkreisRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
