version: '3.8'

#################################
# Volumes (statischer Schlüssel,
# echter Name enthält ENVIRONMENT)
#################################
volumes:
  postgres_data:
    external: false
    name: "postgres_data_${ENVIRONMENT}"

#################################
# Netzwerke
#################################
networks:
  web:
    external: true

  electra_net:
    driver: bridge
    external: false
    name: "electra_${ENVIRONMENT}"

#################################
# Services
#################################
services:

  #################################
  # Frontend-Service
  #################################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: electra-frontend-${ENVIRONMENT}
    env_file:
      - .env
    environment:
      - VITE_API_BASE_URL=http://electra-backend-${ENVIRONMENT}:8000
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.electra-frontend-${ENVIRONMENT}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.electra-frontend-${ENVIRONMENT}.entrypoints=websecure"
      - "traefik.http.routers.electra-frontend-${ENVIRONMENT}.tls=true"
      - "traefik.http.routers.electra-frontend-${ENVIRONMENT}.tls.certresolver=cloudflare"
      - "traefik.http.routers.electra-frontend-${ENVIRONMENT}.middlewares=auth-admin@docker"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - web

  #################################
  # Backend-Service
  #################################
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: electra-backend-${ENVIRONMENT}
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/electra
      - ENVIRONMENT=production
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
              python -c 'import psycopg2; conn = psycopg2.connect(\"dbname=electra user=postgres password=postgres host=db\"); cur = conn.cursor(); cur.execute(\"SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = \'wahl\')\"); is_initialized = cur.fetchone()[0]; cur.close(); conn.close(); exit(0 if is_initialized else 1)' && 
              echo \"Database already initialized, skipping setup...\" || 
              (echo \"Database not initialized, running setup...\" && python database-tools/scripts/setup_database.py) && 
              python run_server.py dev
            "
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.electra-backend-${ENVIRONMENT}.rule=Host(`api.${DOMAIN}`)"
      - "traefik.http.routers.electra-backend-${ENVIRONMENT}.entrypoints=websecure"
      - "traefik.http.routers.electra-backend-${ENVIRONMENT}.tls=true"
      - "traefik.http.routers.electra-backend-${ENVIRONMENT}.tls.certresolver=cloudflare"
    volumes:
      - ./backend:/app
      - ./backend/database-tools:/app/database-tools
      - ./backend/database-tools/sitzverteilung:/app/database-tools/sitzverteilung
      - ./backend/database-tools/topTen:/app/database-tools/topTen
    networks:
      web:
        aliases:
          - "api.${DOMAIN}"
      electra_net:

  #################################
  # Database
  #################################
  db:
    image: postgres:17.1
    container_name: electra-db-${ENVIRONMENT}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=electra
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - electra_net
