# coding: utf-8

"""
    Bundestagswahlsystem API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from .winning_parties_erststimme_inner import WinningPartiesErststimmeInner
from .winning_parties_zweitstimme_inner import WinningPartiesZweitstimmeInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WinningParties(BaseModel):
    """
    WinningParties
    """ # noqa: E501
    erststimme: List[WinningPartiesErststimmeInner]
    zweitstimme: List[WinningPartiesZweitstimmeInner]
    __properties: ClassVar[List[str]] = ["erststimme", "zweitstimme"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WinningParties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in erststimme (list)
        _items = []
        if self.erststimme:
            for _item in self.erststimme:
                if _item:
                    _items.append(_item.to_dict())
            _dict['erststimme'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in zweitstimme (list)
        _items = []
        if self.zweitstimme:
            for _item in self.zweitstimme:
                if _item:
                    _items.append(_item.to_dict())
            _dict['zweitstimme'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WinningParties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "erststimme": [WinningPartiesErststimmeInner.from_dict(_item) for _item in obj.get("erststimme")] if obj.get("erststimme") is not None else None,
            "zweitstimme": [WinningPartiesZweitstimmeInner.from_dict(_item) for _item in obj.get("zweitstimme")] if obj.get("zweitstimme") is not None else None
        })
        return _obj


