/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuslaenderanteilWahlkreiseInner
 */
export interface AuslaenderanteilWahlkreiseInner {
    /**
     * 
     * @type {number}
     * @memberof AuslaenderanteilWahlkreiseInner
     */
    wahlkreisId: number;
    /**
     * 
     * @type {string}
     * @memberof AuslaenderanteilWahlkreiseInner
     */
    wahlkreisName: string;
    /**
     * 
     * @type {number}
     * @memberof AuslaenderanteilWahlkreiseInner
     */
    auslaenderanteil: number;
    /**
     * 
     * @type {number}
     * @memberof AuslaenderanteilWahlkreiseInner
     */
    stimmanteil?: number;
}

/**
 * Check if a given object implements the AuslaenderanteilWahlkreiseInner interface.
 */
export function instanceOfAuslaenderanteilWahlkreiseInner(value: object): value is AuslaenderanteilWahlkreiseInner {
    if (!('wahlkreisId' in value) || value['wahlkreisId'] === undefined) return false;
    if (!('wahlkreisName' in value) || value['wahlkreisName'] === undefined) return false;
    if (!('auslaenderanteil' in value) || value['auslaenderanteil'] === undefined) return false;
    return true;
}

export function AuslaenderanteilWahlkreiseInnerFromJSON(json: any): AuslaenderanteilWahlkreiseInner {
    return AuslaenderanteilWahlkreiseInnerFromJSONTyped(json, false);
}

export function AuslaenderanteilWahlkreiseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuslaenderanteilWahlkreiseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'wahlkreisId': json['wahlkreis_id'],
        'wahlkreisName': json['wahlkreis_name'],
        'auslaenderanteil': json['auslaenderanteil'],
        'stimmanteil': json['stimmanteil'] == null ? undefined : json['stimmanteil'],
    };
}

export function AuslaenderanteilWahlkreiseInnerToJSON(json: any): AuslaenderanteilWahlkreiseInner {
    return AuslaenderanteilWahlkreiseInnerToJSONTyped(json, false);
}

export function AuslaenderanteilWahlkreiseInnerToJSONTyped(value?: AuslaenderanteilWahlkreiseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wahlkreis_id': value['wahlkreisId'],
        'wahlkreis_name': value['wahlkreisName'],
        'auslaenderanteil': value['auslaenderanteil'],
        'stimmanteil': value['stimmanteil'],
    };
}

