/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationDetails
 */
export interface AuthenticationDetails {
    /**
     * Authentication token
     * @type {string}
     * @memberof AuthenticationDetails
     */
    token: string;
    /**
     * Ausweisnummer
     * @type {number}
     * @memberof AuthenticationDetails
     */
    ausweisnummer: number;
}

/**
 * Check if a given object implements the AuthenticationDetails interface.
 */
export function instanceOfAuthenticationDetails(value: object): value is AuthenticationDetails {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('ausweisnummer' in value) || value['ausweisnummer'] === undefined) return false;
    return true;
}

export function AuthenticationDetailsFromJSON(json: any): AuthenticationDetails {
    return AuthenticationDetailsFromJSONTyped(json, false);
}

export function AuthenticationDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'ausweisnummer': json['ausweisnummer'],
    };
}

export function AuthenticationDetailsToJSON(json: any): AuthenticationDetails {
    return AuthenticationDetailsToJSONTyped(json, false);
}

export function AuthenticationDetailsToJSONTyped(value?: AuthenticationDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'ausweisnummer': value['ausweisnummer'],
    };
}

