/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Authentication request
 * @export
 * @interface AuthenticationRequest
 */
export interface AuthenticationRequest {
    /**
     * Authentication token
     * @type {string}
     * @memberof AuthenticationRequest
     */
    token: string;
    /**
     * ID number
     * @type {string}
     * @memberof AuthenticationRequest
     */
    idNumber: string;
}

/**
 * Check if a given object implements the AuthenticationRequest interface.
 */
export function instanceOfAuthenticationRequest(value: object): value is AuthenticationRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('idNumber' in value) || value['idNumber'] === undefined) return false;
    return true;
}

export function AuthenticationRequestFromJSON(json: any): AuthenticationRequest {
    return AuthenticationRequestFromJSONTyped(json, false);
}

export function AuthenticationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'idNumber': json['idNumber'],
    };
}

export function AuthenticationRequestToJSON(json: any): AuthenticationRequest {
    return AuthenticationRequestToJSONTyped(json, false);
}

export function AuthenticationRequestToJSONTyped(value?: AuthenticationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'idNumber': value['idNumber'],
    };
}

