/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Wahl } from './Wahl';
import {
    WahlFromJSON,
    WahlFromJSONTyped,
    WahlToJSON,
    WahlToJSONTyped,
} from './Wahl';
import type { Wahlkreis } from './Wahlkreis';
import {
    WahlkreisFromJSON,
    WahlkreisFromJSONTyped,
    WahlkreisToJSON,
    WahlkreisToJSONTyped,
} from './Wahlkreis';

/**
 * 
 * @export
 * @interface AuthenticatedResponse
 */
export interface AuthenticatedResponse {
    /**
     * 
     * @type {Wahl}
     * @memberof AuthenticatedResponse
     */
    wahl: Wahl;
    /**
     * 
     * @type {Wahlkreis}
     * @memberof AuthenticatedResponse
     */
    wahlkreis: Wahlkreis;
}

/**
 * Check if a given object implements the AuthenticatedResponse interface.
 */
export function instanceOfAuthenticatedResponse(value: object): value is AuthenticatedResponse {
    if (!('wahl' in value) || value['wahl'] === undefined) return false;
    if (!('wahlkreis' in value) || value['wahlkreis'] === undefined) return false;
    return true;
}

export function AuthenticatedResponseFromJSON(json: any): AuthenticatedResponse {
    return AuthenticatedResponseFromJSONTyped(json, false);
}

export function AuthenticatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticatedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'wahl': WahlFromJSON(json['wahl']),
        'wahlkreis': WahlkreisFromJSON(json['wahlkreis']),
    };
}

export function AuthenticatedResponseToJSON(json: any): AuthenticatedResponse {
    return AuthenticatedResponseToJSONTyped(json, false);
}

export function AuthenticatedResponseToJSONTyped(value?: AuthenticatedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wahl': WahlToJSON(value['wahl']),
        'wahlkreis': WahlkreisToJSON(value['wahlkreis']),
    };
}

