/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Bundesland
 */
export interface Bundesland {
    /**
     * 
     * @type {number}
     * @memberof Bundesland
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Bundesland
     */
    name: string;
}

/**
 * Check if a given object implements the Bundesland interface.
 */
export function instanceOfBundesland(value: object): value is Bundesland {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function BundeslandFromJSON(json: any): Bundesland {
    return BundeslandFromJSONTyped(json, false);
}

export function BundeslandFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bundesland {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function BundeslandToJSON(json: any): Bundesland {
    return BundeslandToJSONTyped(json, false);
}

export function BundeslandToJSONTyped(value?: Bundesland | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

