/* tslint:disable */
/* eslint-disable */
/**
 * Donator-Mainframe communication
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Abgeordneter } from './Abgeordneter';
import {
    AbgeordneterFromJSON,
    AbgeordneterFromJSONTyped,
    AbgeordneterToJSON,
    AbgeordneterToJSONTyped,
} from './Abgeordneter';
import type { Wahlkreis } from './Wahlkreis';
import {
    WahlkreisFromJSON,
    WahlkreisFromJSONTyped,
    WahlkreisToJSON,
    WahlkreisToJSONTyped,
} from './Wahlkreis';

/**
 * 
 * @export
 * @interface ClosestWinner
 */
export interface ClosestWinner {
    /**
     * 
     * @type {Abgeordneter}
     * @memberof ClosestWinner
     */
    abgeordneter: Abgeordneter;
    /**
     * 
     * @type {Wahlkreis}
     * @memberof ClosestWinner
     */
    wahlkreis: Wahlkreis;
}

/**
 * Check if a given object implements the ClosestWinner interface.
 */
export function instanceOfClosestWinner(value: object): value is ClosestWinner {
    if (!('abgeordneter' in value) || value['abgeordneter'] === undefined) return false;
    if (!('wahlkreis' in value) || value['wahlkreis'] === undefined) return false;
    return true;
}

export function ClosestWinnerFromJSON(json: any): ClosestWinner {
    return ClosestWinnerFromJSONTyped(json, false);
}

export function ClosestWinnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClosestWinner {
    if (json == null) {
        return json;
    }
    return {
        
        'abgeordneter': AbgeordneterFromJSON(json['abgeordneter']),
        'wahlkreis': WahlkreisFromJSON(json['wahlkreis']),
    };
}

export function ClosestWinnerToJSON(json: any): ClosestWinner {
    return ClosestWinnerToJSONTyped(json, false);
}

export function ClosestWinnerToJSONTyped(value?: ClosestWinner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'abgeordneter': AbgeordneterToJSON(value['abgeordneter']),
        'wahlkreis': WahlkreisToJSON(value['wahlkreis']),
    };
}

