/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Abgeordneter } from './Abgeordneter';
import {
    AbgeordneterFromJSON,
    AbgeordneterFromJSONTyped,
    AbgeordneterToJSON,
    AbgeordneterToJSONTyped,
} from './Abgeordneter';

/**
 * 
 * @export
 * @interface Direktkandidaten
 */
export interface Direktkandidaten {
    /**
     * 
     * @type {Array<Abgeordneter>}
     * @memberof Direktkandidaten
     */
    kandidaten: Array<Abgeordneter>;
}

/**
 * Check if a given object implements the Direktkandidaten interface.
 */
export function instanceOfDirektkandidaten(value: object): value is Direktkandidaten {
    if (!('kandidaten' in value) || value['kandidaten'] === undefined) return false;
    return true;
}

export function DirektkandidatenFromJSON(json: any): Direktkandidaten {
    return DirektkandidatenFromJSONTyped(json, false);
}

export function DirektkandidatenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Direktkandidaten {
    if (json == null) {
        return json;
    }
    return {
        
        'kandidaten': ((json['kandidaten'] as Array<any>).map(AbgeordneterFromJSON)),
    };
}

export function DirektkandidatenToJSON(json: any): Direktkandidaten {
    return DirektkandidatenToJSONTyped(json, false);
}

export function DirektkandidatenToJSONTyped(value?: Direktkandidaten | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kandidaten': ((value['kandidaten'] as Array<any>).map(AbgeordneterToJSON)),
    };
}

