/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EinkommenWahlkreiseInner
 */
export interface EinkommenWahlkreiseInner {
    /**
     * 
     * @type {number}
     * @memberof EinkommenWahlkreiseInner
     */
    wahlkreisId: number;
    /**
     * 
     * @type {string}
     * @memberof EinkommenWahlkreiseInner
     */
    wahlkreisName?: string;
    /**
     * 
     * @type {number}
     * @memberof EinkommenWahlkreiseInner
     */
    einkommen: number;
    /**
     * 
     * @type {number}
     * @memberof EinkommenWahlkreiseInner
     */
    stimmanteil?: number;
}

/**
 * Check if a given object implements the EinkommenWahlkreiseInner interface.
 */
export function instanceOfEinkommenWahlkreiseInner(value: object): value is EinkommenWahlkreiseInner {
    if (!('wahlkreisId' in value) || value['wahlkreisId'] === undefined) return false;
    if (!('einkommen' in value) || value['einkommen'] === undefined) return false;
    return true;
}

export function EinkommenWahlkreiseInnerFromJSON(json: any): EinkommenWahlkreiseInner {
    return EinkommenWahlkreiseInnerFromJSONTyped(json, false);
}

export function EinkommenWahlkreiseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EinkommenWahlkreiseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'wahlkreisId': json['wahlkreis_id'],
        'wahlkreisName': json['wahlkreis_name'] == null ? undefined : json['wahlkreis_name'],
        'einkommen': json['einkommen'],
        'stimmanteil': json['stimmanteil'] == null ? undefined : json['stimmanteil'],
    };
}

export function EinkommenWahlkreiseInnerToJSON(json: any): EinkommenWahlkreiseInner {
    return EinkommenWahlkreiseInnerToJSONTyped(json, false);
}

export function EinkommenWahlkreiseInnerToJSONTyped(value?: EinkommenWahlkreiseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wahlkreis_id': value['wahlkreisId'],
        'wahlkreis_name': value['wahlkreisName'],
        'einkommen': value['einkommen'],
        'stimmanteil': value['stimmanteil'],
    };
}

