/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EinkommenWahlkreiseInner } from './EinkommenWahlkreiseInner';
import {
    EinkommenWahlkreiseInnerFromJSON,
    EinkommenWahlkreiseInnerFromJSONTyped,
    EinkommenWahlkreiseInnerToJSON,
    EinkommenWahlkreiseInnerToJSONTyped,
} from './EinkommenWahlkreiseInner';

/**
 * 
 * @export
 * @interface Einkommen
 */
export interface Einkommen {
    /**
     * 
     * @type {Array<EinkommenWahlkreiseInner>}
     * @memberof Einkommen
     */
    wahlkreise: Array<EinkommenWahlkreiseInner>;
}

/**
 * Check if a given object implements the Einkommen interface.
 */
export function instanceOfEinkommen(value: object): value is Einkommen {
    if (!('wahlkreise' in value) || value['wahlkreise'] === undefined) return false;
    return true;
}

export function EinkommenFromJSON(json: any): Einkommen {
    return EinkommenFromJSONTyped(json, false);
}

export function EinkommenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Einkommen {
    if (json == null) {
        return json;
    }
    return {
        
        'wahlkreise': ((json['wahlkreise'] as Array<any>).map(EinkommenWahlkreiseInnerFromJSON)),
    };
}

export function EinkommenToJSON(json: any): Einkommen {
    return EinkommenToJSONTyped(json, false);
}

export function EinkommenToJSONTyped(value?: Einkommen | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wahlkreise': ((value['wahlkreise'] as Array<any>).map(EinkommenWahlkreiseInnerToJSON)),
    };
}

