/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * generates Tokens
 * @export
 * @interface GenerateToken
 */
export interface GenerateToken {
    /**
     * 
     * @type {number}
     * @memberof GenerateToken
     */
    amount: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof GenerateToken
     */
    idNumbers: Array<string>;
}

/**
 * Check if a given object implements the GenerateToken interface.
 */
export function instanceOfGenerateToken(value: object): value is GenerateToken {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('idNumbers' in value) || value['idNumbers'] === undefined) return false;
    return true;
}

export function GenerateTokenFromJSON(json: any): GenerateToken {
    return GenerateTokenFromJSONTyped(json, false);
}

export function GenerateTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateToken {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'idNumbers': json['idNumbers'],
    };
}

export function GenerateTokenToJSON(json: any): GenerateToken {
    return GenerateTokenToJSONTyped(json, false);
}

export function GenerateTokenToJSONTyped(value?: GenerateToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'idNumbers': value['idNumbers'],
    };
}

