/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateTokenAmountParameter
 */
export interface GenerateTokenAmountParameter {
    /**
     * 
     * @type {number}
     * @memberof GenerateTokenAmountParameter
     */
    amount: number;
}

/**
 * Check if a given object implements the GenerateTokenAmountParameter interface.
 */
export function instanceOfGenerateTokenAmountParameter(value: object): value is GenerateTokenAmountParameter {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function GenerateTokenAmountParameterFromJSON(json: any): GenerateTokenAmountParameter {
    return GenerateTokenAmountParameterFromJSONTyped(json, false);
}

export function GenerateTokenAmountParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateTokenAmountParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
    };
}

export function GenerateTokenAmountParameterToJSON(json: any): GenerateTokenAmountParameter {
    return GenerateTokenAmountParameterToJSONTyped(json, false);
}

export function GenerateTokenAmountParameterToJSONTyped(value?: GenerateTokenAmountParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
    };
}

