/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateToken200ResponseInner
 */
export interface GenerateToken200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof GenerateToken200ResponseInner
     */
    idNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateToken200ResponseInner
     */
    token?: string;
}

/**
 * Check if a given object implements the GenerateToken200ResponseInner interface.
 */
export function instanceOfGenerateToken200ResponseInner(value: object): value is GenerateToken200ResponseInner {
    return true;
}

export function GenerateToken200ResponseInnerFromJSON(json: any): GenerateToken200ResponseInner {
    return GenerateToken200ResponseInnerFromJSONTyped(json, false);
}

export function GenerateToken200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateToken200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'idNumber': json['idNumber'] == null ? undefined : json['idNumber'],
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function GenerateToken200ResponseInnerToJSON(json: any): GenerateToken200ResponseInner {
    return GenerateToken200ResponseInnerToJSONTyped(json, false);
}

export function GenerateToken200ResponseInnerToJSONTyped(value?: GenerateToken200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idNumber': value['idNumber'],
        'token': value['token'],
    };
}

