/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ParteiWahlzettelParteienInner } from './ParteiWahlzettelParteienInner';
import {
    ParteiWahlzettelParteienInnerFromJSON,
    ParteiWahlzettelParteienInnerFromJSONTyped,
    ParteiWahlzettelParteienInnerToJSON,
    ParteiWahlzettelParteienInnerToJSONTyped,
} from './ParteiWahlzettelParteienInner';

/**
 * 
 * @export
 * @interface ParteiWahlzettel
 */
export interface ParteiWahlzettel {
    /**
     * 
     * @type {Array<ParteiWahlzettelParteienInner>}
     * @memberof ParteiWahlzettel
     */
    parteien?: Array<ParteiWahlzettelParteienInner>;
}

/**
 * Check if a given object implements the ParteiWahlzettel interface.
 */
export function instanceOfParteiWahlzettel(value: object): value is ParteiWahlzettel {
    return true;
}

export function ParteiWahlzettelFromJSON(json: any): ParteiWahlzettel {
    return ParteiWahlzettelFromJSONTyped(json, false);
}

export function ParteiWahlzettelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParteiWahlzettel {
    if (json == null) {
        return json;
    }
    return {
        
        'parteien': json['parteien'] == null ? undefined : ((json['parteien'] as Array<any>).map(ParteiWahlzettelParteienInnerFromJSON)),
    };
}

export function ParteiWahlzettelToJSON(json: any): ParteiWahlzettel {
    return ParteiWahlzettelToJSONTyped(json, false);
}

export function ParteiWahlzettelToJSONTyped(value?: ParteiWahlzettel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parteien': value['parteien'] == null ? undefined : ((value['parteien'] as Array<any>).map(ParteiWahlzettelParteienInnerToJSON)),
    };
}

