/* tslint:disable */
/* eslint-disable */
/**
 * Donator-Mainframe communication
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Abgeordneter } from './Abgeordneter';
import {
    AbgeordneterFromJSON,
    AbgeordneterFromJSONTyped,
    AbgeordneterToJSON,
    AbgeordneterToJSONTyped,
} from './Abgeordneter';

/**
 * 
 * @export
 * @interface ResultsWahlidOverviewWahlkreisWahlkreisidGet200Response
 */
export interface ResultsWahlidOverviewWahlkreisWahlkreisidGet200Response {
    /**
     * 
     * @type {number}
     * @memberof ResultsWahlidOverviewWahlkreisWahlkreisidGet200Response
     */
    wahlbeteiligung?: number;
    /**
     * 
     * @type {Abgeordneter}
     * @memberof ResultsWahlidOverviewWahlkreisWahlkreisidGet200Response
     */
    direktkandidat?: Abgeordneter;
}

/**
 * Check if a given object implements the ResultsWahlidOverviewWahlkreisWahlkreisidGet200Response interface.
 */
export function instanceOfResultsWahlidOverviewWahlkreisWahlkreisidGet200Response(value: object): value is ResultsWahlidOverviewWahlkreisWahlkreisidGet200Response {
    return true;
}

export function ResultsWahlidOverviewWahlkreisWahlkreisidGet200ResponseFromJSON(json: any): ResultsWahlidOverviewWahlkreisWahlkreisidGet200Response {
    return ResultsWahlidOverviewWahlkreisWahlkreisidGet200ResponseFromJSONTyped(json, false);
}

export function ResultsWahlidOverviewWahlkreisWahlkreisidGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultsWahlidOverviewWahlkreisWahlkreisidGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'wahlbeteiligung': json['wahlbeteiligung'] == null ? undefined : json['wahlbeteiligung'],
        'direktkandidat': json['direktkandidat'] == null ? undefined : AbgeordneterFromJSON(json['direktkandidat']),
    };
}

export function ResultsWahlidOverviewWahlkreisWahlkreisidGet200ResponseToJSON(json: any): ResultsWahlidOverviewWahlkreisWahlkreisidGet200Response {
    return ResultsWahlidOverviewWahlkreisWahlkreisidGet200ResponseToJSONTyped(json, false);
}

export function ResultsWahlidOverviewWahlkreisWahlkreisidGet200ResponseToJSONTyped(value?: ResultsWahlidOverviewWahlkreisWahlkreisidGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wahlbeteiligung': value['wahlbeteiligung'],
        'direktkandidat': AbgeordneterToJSON(value['direktkandidat']),
    };
}

