/* tslint:disable */
/* eslint-disable */
/**
 * Donator-Mainframe communication
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Partei } from './Partei';
import {
    ParteiFromJSON,
    ParteiFromJSONTyped,
    ParteiToJSON,
    ParteiToJSONTyped,
} from './Partei';

/**
 * 
 * @export
 * @interface SeatDistributionDistributionInner
 */
export interface SeatDistributionDistributionInner {
    /**
     * 
     * @type {Partei}
     * @memberof SeatDistributionDistributionInner
     */
    party: Partei;
    /**
     * 
     * @type {number}
     * @memberof SeatDistributionDistributionInner
     */
    seats: number;
}

/**
 * Check if a given object implements the SeatDistributionDistributionInner interface.
 */
export function instanceOfSeatDistributionDistributionInner(value: object): value is SeatDistributionDistributionInner {
    if (!('party' in value) || value['party'] === undefined) return false;
    if (!('seats' in value) || value['seats'] === undefined) return false;
    return true;
}

export function SeatDistributionDistributionInnerFromJSON(json: any): SeatDistributionDistributionInner {
    return SeatDistributionDistributionInnerFromJSONTyped(json, false);
}

export function SeatDistributionDistributionInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeatDistributionDistributionInner {
    if (json == null) {
        return json;
    }
    return {
        
        'party': ParteiFromJSON(json['party']),
        'seats': json['seats'],
    };
}

export function SeatDistributionDistributionInnerToJSON(json: any): SeatDistributionDistributionInner {
    return SeatDistributionDistributionInnerToJSONTyped(json, false);
}

export function SeatDistributionDistributionInnerToJSONTyped(value?: SeatDistributionDistributionInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'party': ParteiToJSON(value['party']),
        'seats': value['seats'],
    };
}

