/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionToken
 */
export interface SessionToken {
    /**
     * returns a session token
     * @type {string}
     * @memberof SessionToken
     */
    sessionToken?: string;
}

/**
 * Check if a given object implements the SessionToken interface.
 */
export function instanceOfSessionToken(value: object): value is SessionToken {
    return true;
}

export function SessionTokenFromJSON(json: any): SessionToken {
    return SessionTokenFromJSONTyped(json, false);
}

export function SessionTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionToken {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionToken': json['sessionToken'] == null ? undefined : json['sessionToken'],
    };
}

export function SessionTokenToJSON(json: any): SessionToken {
    return SessionTokenToJSONTyped(json, false);
}

export function SessionTokenToJSONTyped(value?: SessionToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionToken': value['sessionToken'],
    };
}

