/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Bundesland } from './Bundesland';
import {
    BundeslandFromJSON,
    BundeslandFromJSONTyped,
    BundeslandToJSON,
    BundeslandToJSONTyped,
} from './Bundesland';

/**
 * 
 * @export
 * @interface UeberhangBundesland
 */
export interface UeberhangBundesland {
    /**
     * 
     * @type {Bundesland}
     * @memberof UeberhangBundesland
     */
    bundesland: Bundesland;
    /**
     * 
     * @type {number}
     * @memberof UeberhangBundesland
     */
    ueberhang: number;
}

/**
 * Check if a given object implements the UeberhangBundesland interface.
 */
export function instanceOfUeberhangBundesland(value: object): value is UeberhangBundesland {
    if (!('bundesland' in value) || value['bundesland'] === undefined) return false;
    if (!('ueberhang' in value) || value['ueberhang'] === undefined) return false;
    return true;
}

export function UeberhangBundeslandFromJSON(json: any): UeberhangBundesland {
    return UeberhangBundeslandFromJSONTyped(json, false);
}

export function UeberhangBundeslandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UeberhangBundesland {
    if (json == null) {
        return json;
    }
    return {
        
        'bundesland': BundeslandFromJSON(json['bundesland']),
        'ueberhang': json['ueberhang'],
    };
}

export function UeberhangBundeslandToJSON(json: any): UeberhangBundesland {
    return UeberhangBundeslandToJSONTyped(json, false);
}

export function UeberhangBundeslandToJSONTyped(value?: UeberhangBundesland | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bundesland': BundeslandToJSON(value['bundesland']),
        'ueberhang': value['ueberhang'],
    };
}

