/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UeberhangBundesland } from './UeberhangBundesland';
import {
    UeberhangBundeslandFromJSON,
    UeberhangBundeslandFromJSONTyped,
    UeberhangBundeslandToJSON,
    UeberhangBundeslandToJSONTyped,
} from './UeberhangBundesland';

/**
 * 
 * @export
 * @interface Ueberhang
 */
export interface Ueberhang {
    /**
     * 
     * @type {Array<UeberhangBundesland>}
     * @memberof Ueberhang
     */
    bundeslaender?: Array<UeberhangBundesland>;
}

/**
 * Check if a given object implements the Ueberhang interface.
 */
export function instanceOfUeberhang(value: object): value is Ueberhang {
    return true;
}

export function UeberhangFromJSON(json: any): Ueberhang {
    return UeberhangFromJSONTyped(json, false);
}

export function UeberhangFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ueberhang {
    if (json == null) {
        return json;
    }
    return {
        
        'bundeslaender': json['bundeslaender'] == null ? undefined : ((json['bundeslaender'] as Array<any>).map(UeberhangBundeslandFromJSON)),
    };
}

export function UeberhangToJSON(json: any): Ueberhang {
    return UeberhangToJSONTyped(json, false);
}

export function UeberhangToJSONTyped(value?: Ueberhang | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bundeslaender': value['bundeslaender'] == null ? undefined : ((value['bundeslaender'] as Array<any>).map(UeberhangBundeslandToJSON)),
    };
}

