/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VoteRequest
 */
export interface VoteRequest {
    /**
     * Authentication token
     * @type {string}
     * @memberof VoteRequest
     */
    token?: string;
    /**
     * Direct Candidate ID
     * @type {number}
     * @memberof VoteRequest
     */
    directCandidateId?: number;
    /**
     * Party ID
     * @type {number}
     * @memberof VoteRequest
     */
    partyId?: number;
}

/**
 * Check if a given object implements the VoteRequest interface.
 */
export function instanceOfVoteRequest(value: object): value is VoteRequest {
    return true;
}

export function VoteRequestFromJSON(json: any): VoteRequest {
    return VoteRequestFromJSONTyped(json, false);
}

export function VoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VoteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
        'directCandidateId': json['directCandidateId'] == null ? undefined : json['directCandidateId'],
        'partyId': json['partyId'] == null ? undefined : json['partyId'],
    };
}

export function VoteRequestToJSON(json: any): VoteRequest {
    return VoteRequestToJSONTyped(json, false);
}

export function VoteRequestToJSONTyped(value?: VoteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'directCandidateId': value['directCandidateId'],
        'partyId': value['partyId'],
    };
}

