/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WahlzettelParteiWrapper } from './WahlzettelParteiWrapper';
import {
    WahlzettelParteiWrapperFromJSON,
    WahlzettelParteiWrapperFromJSONTyped,
    WahlzettelParteiWrapperToJSON,
    WahlzettelParteiWrapperToJSONTyped,
} from './WahlzettelParteiWrapper';

/**
 * 
 * @export
 * @interface WahlzettelParteien
 */
export interface WahlzettelParteien {
    /**
     * 
     * @type {Array<WahlzettelParteiWrapper>}
     * @memberof WahlzettelParteien
     */
    parteien: Array<WahlzettelParteiWrapper>;
}

/**
 * Check if a given object implements the WahlzettelParteien interface.
 */
export function instanceOfWahlzettelParteien(value: object): value is WahlzettelParteien {
    if (!('parteien' in value) || value['parteien'] === undefined) return false;
    return true;
}

export function WahlzettelParteienFromJSON(json: any): WahlzettelParteien {
    return WahlzettelParteienFromJSONTyped(json, false);
}

export function WahlzettelParteienFromJSONTyped(json: any, ignoreDiscriminator: boolean): WahlzettelParteien {
    if (json == null) {
        return json;
    }
    return {
        
        'parteien': ((json['parteien'] as Array<any>).map(WahlzettelParteiWrapperFromJSON)),
    };
}

export function WahlzettelParteienToJSON(json: any): WahlzettelParteien {
    return WahlzettelParteienToJSONTyped(json, false);
}

export function WahlzettelParteienToJSONTyped(value?: WahlzettelParteien | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parteien': ((value['parteien'] as Array<any>).map(WahlzettelParteiWrapperToJSON)),
    };
}

