/* tslint:disable */
/* eslint-disable */
/**
 * Donator-Mainframe communication
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Wahlkreis
 */
export interface Wahlkreis {
    /**
     * 
     * @type {number}
     * @memberof Wahlkreis
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Wahlkreis
     */
    name: string;
}

/**
 * Check if a given object implements the Wahlkreis interface.
 */
export function instanceOfWahlkreis(value: object): value is Wahlkreis {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function WahlkreisFromJSON(json: any): Wahlkreis {
    return WahlkreisFromJSONTyped(json, false);
}

export function WahlkreisFromJSONTyped(json: any, ignoreDiscriminator: boolean): Wahlkreis {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function WahlkreisToJSON(json: any): Wahlkreis {
    return WahlkreisToJSONTyped(json, false);
}

export function WahlkreisToJSONTyped(value?: Wahlkreis | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

