/* tslint:disable */
/* eslint-disable */
/**
 * Bundestagswahlsystem API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Partei } from './Partei';
import {
    ParteiFromJSON,
    ParteiFromJSONTyped,
    ParteiToJSON,
    ParteiToJSONTyped,
} from './Partei';

/**
 * 
 * @export
 * @interface WinningPartiesZweitstimmeInner
 */
export interface WinningPartiesZweitstimmeInner {
    /**
     * 
     * @type {Partei}
     * @memberof WinningPartiesZweitstimmeInner
     */
    party: Partei;
    /**
     * 
     * @type {number}
     * @memberof WinningPartiesZweitstimmeInner
     */
    regionId: number;
    /**
     * 
     * @type {number}
     * @memberof WinningPartiesZweitstimmeInner
     */
    regionName: number;
}

/**
 * Check if a given object implements the WinningPartiesZweitstimmeInner interface.
 */
export function instanceOfWinningPartiesZweitstimmeInner(value: object): value is WinningPartiesZweitstimmeInner {
    if (!('party' in value) || value['party'] === undefined) return false;
    if (!('regionId' in value) || value['regionId'] === undefined) return false;
    if (!('regionName' in value) || value['regionName'] === undefined) return false;
    return true;
}

export function WinningPartiesZweitstimmeInnerFromJSON(json: any): WinningPartiesZweitstimmeInner {
    return WinningPartiesZweitstimmeInnerFromJSONTyped(json, false);
}

export function WinningPartiesZweitstimmeInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): WinningPartiesZweitstimmeInner {
    if (json == null) {
        return json;
    }
    return {
        
        'party': ParteiFromJSON(json['party']),
        'regionId': json['region_id'],
        'regionName': json['region_name'],
    };
}

export function WinningPartiesZweitstimmeInnerToJSON(json: any): WinningPartiesZweitstimmeInner {
    return WinningPartiesZweitstimmeInnerToJSONTyped(json, false);
}

export function WinningPartiesZweitstimmeInnerToJSONTyped(value?: WinningPartiesZweitstimmeInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'party': ParteiToJSON(value['party']),
        'region_id': value['regionId'],
        'region_name': value['regionName'],
    };
}

