/* tslint:disable */
/* eslint-disable */
/**
 * Donator-Mainframe communication
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Partei } from './Partei';
import {
    ParteiFromJSON,
    ParteiFromJSONTyped,
    ParteiToJSON,
    ParteiToJSONTyped,
} from './Partei';

/**
 * 
 * @export
 * @interface WinningParties
 */
export interface WinningParties {
    /**
     * 
     * @type {Partei}
     * @memberof WinningParties
     */
    erststimmen: Partei;
    /**
     * 
     * @type {Partei}
     * @memberof WinningParties
     */
    zweitstimmen: Partei;
}

/**
 * Check if a given object implements the WinningParties interface.
 */
export function instanceOfWinningParties(value: object): value is WinningParties {
    if (!('erststimmen' in value) || value['erststimmen'] === undefined) return false;
    if (!('zweitstimmen' in value) || value['zweitstimmen'] === undefined) return false;
    return true;
}

export function WinningPartiesFromJSON(json: any): WinningParties {
    return WinningPartiesFromJSONTyped(json, false);
}

export function WinningPartiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): WinningParties {
    if (json == null) {
        return json;
    }
    return {
        
        'erststimmen': ParteiFromJSON(json['Erststimmen']),
        'zweitstimmen': ParteiFromJSON(json['Zweitstimmen']),
    };
}

export function WinningPartiesToJSON(json: any): WinningParties {
    return WinningPartiesToJSONTyped(json, false);
}

export function WinningPartiesToJSONTyped(value?: WinningParties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Erststimmen': ParteiToJSON(value['erststimmen']),
        'Zweitstimmen': ParteiToJSON(value['zweitstimmen']),
    };
}

