# coding: utf-8

"""
    Donator-Mainframe communication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.abgeordneter import Abgeordneter
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OverviewWahlkreis(BaseModel):
    """
    OverviewWahlkreis
    """ # noqa: E501
    wahlbeteiligung: Optional[Union[StrictFloat, StrictInt]] = None
    direktkandidat: Optional[Abgeordneter] = None
    __properties: ClassVar[List[str]] = ["wahlbeteiligung", "direktkandidat"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OverviewWahlkreis from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of direktkandidat
        if self.direktkandidat:
            _dict['direktkandidat'] = self.direktkandidat.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OverviewWahlkreis from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "wahlbeteiligung": obj.get("wahlbeteiligung"),
            "direktkandidat": Abgeordneter.from_dict(obj.get("direktkandidat")) if obj.get("direktkandidat") is not None else None
        })
        return _obj


