# coding: utf-8
"""
    Donator-Mainframe communication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import os
from typing import List

from .apis.general_api import router as GeneralApiRouter
from .apis.global_api import router as GlobalApiRouter
from .apis.wahlkreis_api import router as WahlkreisApiRouter
from .apis.elect_api import router as ElectApiRouter
from .apis.admin_api import router as AdminApiRouter
from .apis.analysis_api import router as AnalysisApiRouter



# Create FastAPI app
app = FastAPI(
    title="Donator-Mainframe communication",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="0.1.0",
)

# Get CORS origins from environment variable
# Format: "http://localhost:5173,http://localhost:4173"
origins_env = os.getenv("ALLOWED_ORIGINS", "http://localhost:5173,http://localhost:4173")
origins: List[str] = origins_env.split(",")

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include API routers
app.include_router(GeneralApiRouter)
app.include_router(GlobalApiRouter)
app.include_router(WahlkreisApiRouter)
app.include_router(ElectApiRouter)
app.include_router(AdminApiRouter)
app.include_router(AnalysisApiRouter)
