# coding: utf-8
#start-up with: uvicorn main:app --reload


"""
    Donator-Mainframe communication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.general_api import router as GeneralApiRouter
from openapi_server.apis.global_api import router as GlobalApiRouter
from openapi_server.apis.wahlkreis_api import router as WahlkreisApiRouter

app = FastAPI(
    title="Donator-Mainframe communication",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="0.1.0",
)

app.include_router(GeneralApiRouter)
app.include_router(GlobalApiRouter)
app.include_router(WahlkreisApiRouter)
