# coding: utf-8
# installation with: uv pip install -e .
# Start-up with: uvicorn main:app --reload

"""
    Donator-Mainframe communication

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from openapi_server.apis.general_api import router as GeneralApiRouter
from openapi_server.apis.global_api import router as GlobalApiRouter
from openapi_server.apis.wahlkreis_api import router as WahlkreisApiRouter

# Create FastAPI app
app = FastAPI(
    title="Donator-Mainframe communication",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="0.1.0",
)

# Configure CORS
origins = [
    "http://localhost:5173",  # Frontend origin (replace with actual URL in production)
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,  # Allow specific origins
    allow_credentials=True,  # Allow cookies and authorization headers
    allow_methods=["*"],  # Allow all HTTP methods (GET, POST, etc.)
    allow_headers=["*"],  # Allow all headers (Authorization, Content-Type, etc.)
)

# Include API routers
app.include_router(GeneralApiRouter)
app.include_router(GlobalApiRouter)
app.include_router(WahlkreisApiRouter)
